# docker-compose.yml
version: '3.7'
services:
  jenkins:
    image: jenkins_custom
    privileged: true
    user: root
    ports:
      - 1234:8080
      - 5678:50000
    container_name: jenkins-corner
    volumes:
     - ./jenkins_data:/var/jenkins_home

